# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:beast/animations/throw_area/zzz/apply_frame {frame: 65}
scoreboard players add @s aj.throw_area.frame 1