# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:jaw/animations/climb_front/zzz/apply_frame {frame: 25}
scoreboard players add @s aj.climb_front.frame 1