# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data merge value {"locators":{"consume":{"posx":-3.875,"posy":-8.875,"posz":-2.4375000000000004,"roty":0,"rotx":0}},"cameras":{}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:beast/animations/bite/zzz/frames/zzz/3