# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.jaw.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'jaw', 'function_path': 'animated_java:jaw/animations/charge_init/next_frame'}
execute if score @s aj.charge_init.frame matches 61.. run scoreboard players set @s aj.charge_init.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.charge_init.frame
execute at @s run function animated_java:jaw/animations/charge_init/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.charge_init.frame 1