# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.armor.root] run return 0
execute on passengers if entity @s[tag=aj.armor.data] unless data entity @s {data:{rigHash: 'f326591ef1ce8d4bcf7624f1a86f053c4d071f08c5de38abe3b7a2fb1874e8ad'}} on vehicle run function animated_java:armor/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1