# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.armor.root] run return 0
execute on passengers if entity @s[tag=aj.armor.data] unless data entity @s {data:{rigHash: '32c8a0d63886dc7c903c1ccb1ede4375d9f0cc9dc36d3be5da630674c8741575'}} on vehicle run function animated_java:armor/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1