# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.armor.root] run return 0
execute on passengers if entity @s[tag=aj.armor.data] unless data entity @s {data:{rigHash: '4d1a1b452a9c31a995e9110ae6640f55e2c3f6094b1e7e2f5166cbd00470aed9'}} on vehicle run function animated_java:armor/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1