# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:jaw/animations/sneak_loop/zzz/apply_frame {frame: 560}
scoreboard players add @s aj.sneak_loop.frame 1