# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:armor/animations/charge/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.charge.frame 1