# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:armor_stand ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.attack.locator', 'aj.attack.locator.consume']}
execute as @e[type=minecraft:armor_stand,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:attack/zzz/2
data modify entity @s data.locators.consume.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.neck] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_thumb_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_thumb_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_thumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_thumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_fingers2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_fingers2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_fingers] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_fingers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_bicep] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_bicep set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_shoulder] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_shoulder set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_thumb_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_thumb_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_thumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_thumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_fingers2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_fingers2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_fingers] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_fingers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_bicep] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_bicep set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_shoulder] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_shoulder set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.chest] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.weist] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_weist set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_knee] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_knee set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_thigh] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_thigh set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_knee] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_knee set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_thigh] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_thigh set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.attack.bone.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out