# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:jaw/animations/sneak.loop/zzz/apply_frame {frame: 560}
scoreboard players add @s aj.sneak.loop.frame 1