# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.jaw.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'jaw', 'function_path': 'animated_java:jaw/animations/pause_all'}
tag @s remove aj.jaw.animation.run.playing
tag @s remove aj.jaw.animation.idle.playing
tag @s remove aj.jaw.animation.born.playing
tag @s remove aj.jaw.animation.death.playing
tag @s remove aj.jaw.animation.walk.playing
tag @s remove aj.jaw.animation.sneak.playing
tag @s remove aj.jaw.animation.walk_left.playing
tag @s remove aj.jaw.animation.walk_right.playing
tag @s remove aj.jaw.animation.walk_front.playing
tag @s remove aj.jaw.animation.jump.playing
tag @s remove aj.jaw.animation.bite.playing
tag @s remove aj.jaw.animation.roar.playing
tag @s remove aj.jaw.animation.charge_init.playing
tag @s remove aj.jaw.animation.charge_end.playing
tag @s remove aj.jaw.animation.climb_front.playing