# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.beast.root] run return 0
execute on passengers if entity @s[tag=aj.beast.data] unless data entity @s {data:{rigHash: 'aab8058ab2816c203bc627d2d32572d7d57afca8fa078423ea98e04b0687a63c'}} on vehicle run function animated_java:beast/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1