# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.beast.root] run return 0
execute on passengers if entity @s[tag=aj.beast.data] unless data entity @s {data:{rigHash: '2cb28e1623f5f9ffdb9475a1baec9b6df8375a5c76eba73d4efbee53c3228fb1'}} on vehicle run function animated_java:beast/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1