# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.beast.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:beast/as_root/pre_tick
execute if entity @s[tag=aj.beast.animation.idle.playing] run function animated_java:beast/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.beast.animation.walk.playing] run function animated_java:beast/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.beast.animation.throw_big.playing] run function animated_java:beast/animations/throw_big/zzz/on_tick
execute if entity @s[tag=aj.beast.animation.throw_area.playing] run function animated_java:beast/animations/throw_area/zzz/on_tick
execute if entity @s[tag=aj.beast.animation.born.playing] run function animated_java:beast/animations/born/zzz/on_tick
execute if entity @s[tag=aj.beast.animation.death.playing] run function animated_java:beast/animations/death/zzz/on_tick
execute if entity @s[tag=aj.beast.animation.grab.playing] run function animated_java:beast/animations/grab/zzz/on_tick
execute if entity @s[tag=aj.beast.animation.sneak.playing] run function animated_java:beast/animations/sneak/zzz/on_tick
execute if entity @s[tag=aj.beast.animation.consume.playing] run function animated_java:beast/animations/consume/zzz/on_tick
execute if entity @s[tag=aj.beast.animation.slap.playing] run function animated_java:beast/animations/slap/zzz/on_tick
execute on passengers if entity @s[tag=aj.beast.data] run function animated_java:beast/root/zzz/1
execute at @s on passengers run rotate @s ~ ~
function #animated_java:beast/as_root/post_tick