# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.attack.root] run return 0
execute on passengers if entity @s[tag=aj.attack.data] unless data entity @s {data:{rigHash: '4eb39940881fc6a658c2c616291713186c7f151761d4dd70c76527c4e57daa6f'}} on vehicle run function animated_java:attack/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1