# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.attack.root] run return 0
execute on passengers if entity @s[tag=aj.attack.data] unless data entity @s {data:{rigHash: '1fecd583d553f88cf5a53dc7c4e3a98ebbdbe93334affec40fc9269043815f59'}} on vehicle run function animated_java:attack/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1