# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.attack.root] run return 0
execute on passengers if entity @s[tag=aj.attack.data] unless data entity @s {data:{rigHash: 'ccc421b6e12ffb28858e6ab038532e7464679d23307a1e5c8f46787730f3b91f'}} on vehicle run function animated_java:attack/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1