# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.attack.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:attack/as_root/pre_tick
execute if entity @s[tag=aj.attack.animation.walk.playing] run function animated_java:attack/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.idle.playing] run function animated_java:attack/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.punch_1.playing] run function animated_java:attack/animations/punch_1/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.punch_2.playing] run function animated_java:attack/animations/punch_2/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.punch_3.playing] run function animated_java:attack/animations/punch_3/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.death.playing] run function animated_java:attack/animations/death/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.born.playing] run function animated_java:attack/animations/born/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.sneak.playing] run function animated_java:attack/animations/sneak/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.consume.playing] run function animated_java:attack/animations/consume/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.kick_1.playing] run function animated_java:attack/animations/kick_1/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.kick_2.playing] run function animated_java:attack/animations/kick_2/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.kick_3.playing] run function animated_java:attack/animations/kick_3/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.block.playing] run function animated_java:attack/animations/block/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.jump.playing] run function animated_java:attack/animations/jump/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.bite.playing] run function animated_java:attack/animations/bite/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.roar.playing] run function animated_java:attack/animations/roar/zzz/on_tick
execute if entity @s[tag=aj.attack.animation.run.playing] run function animated_java:attack/animations/run/zzz/on_tick
execute on passengers if entity @s[tag=aj.attack.data] run function animated_java:attack/root/zzz/1
execute at @s on passengers run rotate @s ~ ~
function #animated_java:attack/as_root/post_tick