# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.sneak.frame
function animated_java:jaw/animations/sneak/zzz/apply_frame with storage aj:temp
execute if score @s aj.sneak.frame matches 10.. run return run function animated_java:jaw/animations/sneak/pause
scoreboard players add @s aj.sneak.frame 1