# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.run.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.punch_1.frame dummy
scoreboard objectives add aj.punch_2.frame dummy
scoreboard objectives add aj.punch_3.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.born.frame dummy
scoreboard objectives add aj.sneak.frame dummy
scoreboard objectives add aj.consume.frame dummy
scoreboard objectives add aj.kick_1.frame dummy
scoreboard objectives add aj.kick_2.frame dummy
scoreboard objectives add aj.kick_3.frame dummy
scoreboard objectives add aj.block.frame dummy
execute as @e[type=item_display,tag=aj.attack.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:attack/root/on_load