# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:armor/animations/jump_loop/zzz/apply_frame {frame: 35}
scoreboard players add @s aj.jump_loop.frame 1