# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.attack.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'attack', 'function_path': 'animated_java:attack/animations/born/next_frame'}
execute if score @s aj.born.frame matches 42.. run scoreboard players set @s aj.born.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.born.frame
execute at @s run function animated_java:attack/animations/born/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.born.frame 1