# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle run attribute @s minecraft:generic.scale base set 1.3
playsound minecraft:aot.footsteps master @a
execute on vehicle anchored feet run particle minecraft:block{block_state:"sand"} ^ ^ ^ 1.5 0 1.5 1 30 force