# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle if predicate snc:player/on_ground at @s run function snc:shifters/mobs/jaw/action/movement/step
execute on vehicle at @s if block ~ ~-.01 ~ #snc:tangible at @s rotated ~ -8.5 run function snc:logic/motion/generic {"score":"jaw_vars","strength":0.014}