# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle run attribute @s scale base set 1.4
execute on vehicle if score $air jaw_vars matches 0 at @s run function snc:shifters/mobs/jaw/action/movement/step