# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function snc:shifters/mobs/jaw/action/movement/air
execute on vehicle if score $air jaw_vars matches 0 at @s rotated ~7 -8 run function snc:logic/motion/generic {"score":"jaw_vars","strength":0.025, "unstoppable":"false"}