# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.beast.root] run return 0
execute on passengers if entity @s[tag=aj.beast.data] unless data entity @s {data:{rigHash: '8147d85a8fd50cd77d9dc1ee7735cc13accf72a6ddf2c5432cc3a4607bacb598'}} on vehicle run function animated_java:beast/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1