# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.beast.root] run return 0
execute on passengers if entity @s[tag=aj.beast.data] unless data entity @s {data:{rigHash: '787e8831ab48ea3bb7e24faf29d7502d526ef98cf7f4bcf1a35a3ba8976736e9'}} on vehicle run function animated_java:beast/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1