# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.neck] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_fingers_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_fingers_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_fingers] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_fingers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_index_finger_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_index_finger_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_index_finger] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_index_finger set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_thumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_thumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_bicep] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_bicep set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_shoulder] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_shoulder set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_fingers_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_fingers_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_fingers] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_fingers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_index_finger_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_index_finger_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_index_finger] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_index_finger set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_thumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_thumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_bicep] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_bicep set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_shoulder] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_shoulder set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.chest] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.weist] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_weist set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_fingers2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_fingers2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_knee] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_knee set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_thigh] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_thigh set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.left_fingers2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_fingers2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_knee] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_knee set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_thigh] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_thigh set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out