# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle run effect give @s slowness 4 127 true
execute on vehicle run attribute @s scale base set 9.2