# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.jaw.root] run return 0
execute on passengers if entity @s[tag=aj.jaw.data] unless data entity @s {data:{rigHash: 'cceb7b6d9c5e83485c353f534f1dffaf636280a907ec497bb9251092cc404ebe'}} on vehicle run function animated_java:jaw/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1