# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.jaw.root] run return 0
execute on passengers if entity @s[tag=aj.jaw.data] unless data entity @s {data:{rigHash: '051e731e32c585b3db5dd1e6dd6d13193e5cf04dcdb81208900e6f217cb0ad6e'}} on vehicle run function animated_java:jaw/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1