# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.attack.root] run return 0
execute on passengers if entity @s[tag=aj.attack.data] unless data entity @s {data:{rigHash: '5cf7bccefebf124398ff32895ad0d7f258781f2c0b479a03514ab45c66f499ac'}} on vehicle run function animated_java:attack/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1