# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:armor_stand ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.beast.locator', 'aj.beast.locator.consume']}
execute as @e[type=minecraft:armor_stand,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:beast/zzz/2
data modify entity @s data.locators.consume.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_thumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_thumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_fingers_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_fingers_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_fingers] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_fingers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_bicep] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_bicep set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_thumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_thumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_fingers_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_fingers_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_fingers] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_fingers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_bicep] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_bicep set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.chest] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.waist] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_waist set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.hip] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hip set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_knee] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_knee set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_thigh] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_thigh set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_knee] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_knee set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_thigh] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_thigh set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.beast.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out