# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.beast.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'beast', 'function_path': 'animated_java:beast/animations/consume/next_frame'}
execute if score @s aj.consume.frame matches 71.. run scoreboard players set @s aj.consume.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.consume.frame
execute at @s run function animated_java:beast/animations/consume/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.consume.frame 1