# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function snc:shifters/mobs/beast/action/movement/step
execute on vehicle run attribute @s minecraft:scale base set 9.5