# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.attack.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'attack', 'function_path': 'animated_java:attack/animations/pause_all'}
tag @s remove aj.attack.animation.walk.playing
tag @s remove aj.attack.animation.idle.playing
tag @s remove aj.attack.animation.punch_1.playing
tag @s remove aj.attack.animation.punch_2.playing
tag @s remove aj.attack.animation.punch_3.playing
tag @s remove aj.attack.animation.death.playing
tag @s remove aj.attack.animation.born.playing
tag @s remove aj.attack.animation.sneak.playing
tag @s remove aj.attack.animation.consume.playing
tag @s remove aj.attack.animation.kick_1.playing
tag @s remove aj.attack.animation.kick_2.playing
tag @s remove aj.attack.animation.kick_3.playing
tag @s remove aj.attack.animation.block.playing
tag @s remove aj.attack.animation.bite.playing
tag @s remove aj.attack.animation.roar.playing
tag @s remove aj.attack.animation.run.playing
tag @s remove aj.attack.animation.jump_init.playing
tag @s remove aj.attack.animation.jump_loop.playing
tag @s remove aj.attack.animation.jump_end.playing