# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.armor.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'armor', 'function_path': 'animated_java:armor/animations/punch_1/stop'}
tag @s remove aj.armor.animation.punch_1.playing
scoreboard players set @s aj.punch_1.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:armor/animations/punch_1/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only