# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.mid] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.teeth] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_teeth set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.skull] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skull set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.tonge] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tonge set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.mid2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mid2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.teeth2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_teeth2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.neck] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_fingers_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_fingers_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_fingers] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_fingers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_index_finger_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_index_finger_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_index_finger] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_index_finger set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_thumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_thumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_bicep] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_bicep set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_shoulder] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_shoulder set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_fingers_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_fingers_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_fingers] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_fingers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_index_finger_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_index_finger_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_index_finger] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_index_finger set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_thumb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_thumb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_bicep] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_bicep set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_shoulder] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_shoulder set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.chest] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.weist] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_weist set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_fingers2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_fingers2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_knee] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_knee set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_thigh] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_thigh set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.left_fingers2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_fingers2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_knee] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_knee set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_thigh] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_thigh set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jaw.bone.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out