# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.jaw.root] run return 0
execute on passengers if entity @s[tag=aj.jaw.data] unless data entity @s {data:{rigHash: '749cfec9d12474315a128f300f6af96d86b09843b9369f068f1dba186754478e'}} on vehicle run function animated_java:jaw/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1