# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.jaw.root] run return 0
execute on passengers if entity @s[tag=aj.jaw.data] unless data entity @s {data:{rigHash: 'af72b55d986e6a7f148e9ca9c2f88c9eae5505725829f38799741cd41e19f7ce'}} on vehicle run function animated_java:jaw/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1