# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.jaw.root] run return 0
execute on passengers if entity @s[tag=aj.jaw.data] unless data entity @s {data:{rigHash: '46deb407a7bbffbb25906165fa58881e65e105c415ac0c8bff1a282cabee0498'}} on vehicle run function animated_java:jaw/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1