# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.jaw.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:jaw/as_root/pre_tick
execute if entity @s[tag=aj.jaw.animation.run.playing] run function animated_java:jaw/animations/run/zzz/on_tick
execute if entity @s[tag=aj.jaw.animation.idle.playing] run function animated_java:jaw/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.jaw.animation.born.playing] run function animated_java:jaw/animations/born/zzz/on_tick
execute if entity @s[tag=aj.jaw.animation.death.playing] run function animated_java:jaw/animations/death/zzz/on_tick
execute if entity @s[tag=aj.jaw.animation.walk.playing] run function animated_java:jaw/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.jaw.animation.sneak.playing] run function animated_java:jaw/animations/sneak/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:jaw/as_root/post_tick