# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.beast.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'beast', 'function_path': 'animated_java:beast/variants/noskin_10/apply'}
execute on passengers if entity @s[tag=aj.beast.bone.right_thumb] run function animated_java:beast/variants/noskin_10/zzz/0
execute on passengers if entity @s[tag=aj.beast.bone.right_fingers_2] run function animated_java:beast/variants/noskin_10/zzz/1
execute on passengers if entity @s[tag=aj.beast.bone.right_fingers] run function animated_java:beast/variants/noskin_10/zzz/2
execute on passengers if entity @s[tag=aj.beast.bone.right_hand] run function animated_java:beast/variants/noskin_10/zzz/3
execute on passengers if entity @s[tag=aj.beast.bone.right_forearm] run function animated_java:beast/variants/noskin_10/zzz/4
execute on passengers if entity @s[tag=aj.beast.bone.right_bicep] run function animated_java:beast/variants/noskin_10/zzz/5
execute on passengers if entity @s[tag=aj.beast.bone.right_arm] run function animated_java:beast/variants/noskin_10/zzz/6
execute on passengers if entity @s[tag=aj.beast.bone.left_thumb] run function animated_java:beast/variants/noskin_10/zzz/7
execute on passengers if entity @s[tag=aj.beast.bone.left_fingers_2] run function animated_java:beast/variants/noskin_10/zzz/8
execute on passengers if entity @s[tag=aj.beast.bone.left_fingers] run function animated_java:beast/variants/noskin_10/zzz/9
execute on passengers if entity @s[tag=aj.beast.bone.left_hand] run function animated_java:beast/variants/noskin_10/zzz/10
execute on passengers if entity @s[tag=aj.beast.bone.left_forearm] run function animated_java:beast/variants/noskin_10/zzz/11
execute on passengers if entity @s[tag=aj.beast.bone.left_bicep] run function animated_java:beast/variants/noskin_10/zzz/12
execute on passengers if entity @s[tag=aj.beast.bone.left_arm] run function animated_java:beast/variants/noskin_10/zzz/13
execute on passengers if entity @s[tag=aj.beast.bone.chest] run function animated_java:beast/variants/noskin_10/zzz/14
execute on passengers if entity @s[tag=aj.beast.bone.waist] run function animated_java:beast/variants/noskin_10/zzz/15
execute on passengers if entity @s[tag=aj.beast.bone.hip] run function animated_java:beast/variants/noskin_10/zzz/16
execute on passengers if entity @s[tag=aj.beast.bone.right_foot] run function animated_java:beast/variants/noskin_10/zzz/17
execute on passengers if entity @s[tag=aj.beast.bone.right_knee] run function animated_java:beast/variants/noskin_10/zzz/18
execute on passengers if entity @s[tag=aj.beast.bone.right_thigh] run function animated_java:beast/variants/noskin_10/zzz/19
execute on passengers if entity @s[tag=aj.beast.bone.right_leg] run function animated_java:beast/variants/noskin_10/zzz/20
execute on passengers if entity @s[tag=aj.beast.bone.left_foot] run function animated_java:beast/variants/noskin_10/zzz/21
execute on passengers if entity @s[tag=aj.beast.bone.left_knee] run function animated_java:beast/variants/noskin_10/zzz/22
execute on passengers if entity @s[tag=aj.beast.bone.left_thigh] run function animated_java:beast/variants/noskin_10/zzz/23
execute on passengers if entity @s[tag=aj.beast.bone.left_leg] run function animated_java:beast/variants/noskin_10/zzz/24