# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.jaw.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'jaw', 'function_path': 'animated_java:jaw/animations/climb.front/play'}
tag @s add aj.jaw.animation.climb.front.playing
scoreboard players set @s aj.climb.front.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:jaw/animations/climb.front/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only