# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.attack.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'attack', 'function_path': 'animated_java:attack/animations/jumpold/play'}
tag @s add aj.attack.animation.jumpold.playing
scoreboard players set @s aj.jumpold.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:attack/animations/jumpold/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only