# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.beast.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'beast', 'function_path': 'animated_java:beast/animations/pause_all'}
tag @s remove aj.beast.animation.idle.playing
tag @s remove aj.beast.animation.walk.playing
tag @s remove aj.beast.animation.throw_big.playing
tag @s remove aj.beast.animation.throw_area.playing
tag @s remove aj.beast.animation.born.playing
tag @s remove aj.beast.animation.death.playing
tag @s remove aj.beast.animation.grab.playing
tag @s remove aj.beast.animation.sneak.playing
tag @s remove aj.beast.animation.consume.playing
tag @s remove aj.beast.animation.slap.playing
tag @s remove aj.beast.animation.bite.playing
tag @s remove aj.beast.animation.roar.playing