# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.jaw.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'jaw', 'function_path': 'animated_java:jaw/variants/decay9/apply'}
execute on passengers if entity @s[tag=aj.jaw.bone.neck] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_neck
execute on passengers if entity @s[tag=aj.jaw.bone.left_fingers_2] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_fingers_2
execute on passengers if entity @s[tag=aj.jaw.bone.left_fingers] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_fingers
execute on passengers if entity @s[tag=aj.jaw.bone.left_index_finger_2] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_index_finger_2
execute on passengers if entity @s[tag=aj.jaw.bone.left_index_finger] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_index_finger
execute on passengers if entity @s[tag=aj.jaw.bone.left_thumb] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_thumb
execute on passengers if entity @s[tag=aj.jaw.bone.left_hand] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_hand
execute on passengers if entity @s[tag=aj.jaw.bone.left_forearm] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_forearm
execute on passengers if entity @s[tag=aj.jaw.bone.left_bicep] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_bicep
execute on passengers if entity @s[tag=aj.jaw.bone.left_shoulder] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_shoulder
execute on passengers if entity @s[tag=aj.jaw.bone.right_fingers_2] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_fingers_2
execute on passengers if entity @s[tag=aj.jaw.bone.right_fingers] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_fingers
execute on passengers if entity @s[tag=aj.jaw.bone.right_index_finger_2] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_index_finger_2
execute on passengers if entity @s[tag=aj.jaw.bone.right_index_finger] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_index_finger
execute on passengers if entity @s[tag=aj.jaw.bone.right_thumb] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_thumb
execute on passengers if entity @s[tag=aj.jaw.bone.right_hand] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_hand
execute on passengers if entity @s[tag=aj.jaw.bone.right_forearm] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_forearm
execute on passengers if entity @s[tag=aj.jaw.bone.right_bicep] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_bicep
execute on passengers if entity @s[tag=aj.jaw.bone.right_shoulder] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_shoulder
execute on passengers if entity @s[tag=aj.jaw.bone.chest] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_chest
execute on passengers if entity @s[tag=aj.jaw.bone.weist] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_weist
execute on passengers if entity @s[tag=aj.jaw.bone.right_fingers2] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_fingers2
execute on passengers if entity @s[tag=aj.jaw.bone.left_foot] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_foot
execute on passengers if entity @s[tag=aj.jaw.bone.left_knee] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_knee
execute on passengers if entity @s[tag=aj.jaw.bone.left_thigh] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_thigh
execute on passengers if entity @s[tag=aj.jaw.bone.left_leg] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_leg
execute on passengers if entity @s[tag=aj.jaw.bone.left_fingers2] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_left_fingers2
execute on passengers if entity @s[tag=aj.jaw.bone.right_foot] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_foot
execute on passengers if entity @s[tag=aj.jaw.bone.right_knee] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_knee
execute on passengers if entity @s[tag=aj.jaw.bone.right_thigh] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_thigh
execute on passengers if entity @s[tag=aj.jaw.bone.right_leg] run function animated_java:jaw/variants/decay9/zzz/apply_to_bone_right_leg
return 1