# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.armor.root] run return 0
execute on passengers if entity @s[tag=aj.armor.data] unless data entity @s {data:{rigHash: 'e64d3afcdce21080e70889114f6df01b80f8654e20e46f703f10e6c1fbe17194'}} on vehicle run function animated_java:armor/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1